CREATE TABLE EPNX_TRANSACTIONS (
  TRANS_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  TRANSACTION_NAME VARCHAR(10000) NOT NULL,
  TRANSACTION_DATE TIMESTAMP NOT NULL,
  REF_NUM VARCHAR(500) NOT NULL UNIQUE,
  VAL_DATE TIMESTAMP NOT NULL,
  WITHDRAW_AMT DECIMAL(19, 4),
  DEPOSIT_AMT DECIMAL(19, 4),
  CREATE_DT TIMESTAMP,
  UPDATED_DT TIMESTAMP,
  CREATED_BY VARCHAR(50)
);